# Generated by Django 5.0.6 on 2024-07-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(max_length=5, null=True)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('financial_data', models.TextField(null=True)),
            ],
        ),
    ]
