# Generated by Django 5.0.6 on 2024-07-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='financial_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='date',
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='symbol',
            field=models.TextField(null=True),
        ),
    ]
