# Generated by Django 5.0.6 on 2024-07-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_alter_stockdata_data_alter_stockdata_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='symbol',
            field=models.TextField(unique=True),
        ),
    ]
